### ISSUE TITLE
Only attempt to show block information if `blocksummary` is set

### ISSUE THREAD

**Issue by samtarling** [GeneralNotability/bullseye#4]
In [blocks.html](https://github.com/GeneralNotability/bullseye/blob/main/bullseyeapp/templates/bullseye/data_components/blocks.html), ensure `blocksummary` is set before attempting to display the accordion.

Consideration to the edge case that `blocksummary` is *not* set but other inner variables (`globalblocks`, `blocks` etc) *are* - is this possible?

PR incoming 😄

**Comment by GeneralNotability** [comment]
I believe you're correct - blocksummary can only be set if there's content to display.
